nginx:
  image: nginx
  links:
    - php
  volumes:
    - ./project:/www  #папка с проектом
    - ./docker/nginx/conf.d:/etc/nginx/conf.d # - advanced
    #- ./docker/nginx/conf.d:/etc/nginx/conf.d-basic # - basic
  ports:
    - 80:80
    - 443:443
php:
  build: docker/php/build
  links:
    - mysql
  volumes:
    - ./project:/www
    - ./projectnew:/www2
    - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
  working_dir: /www/

mysql:
  volumes:
    - ./db:/var/lib/mysql
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 12345
    MYSQL_DATABASE: test
  command: mysqld --sql_mode=""
  ports:
    - 3306:3306